# 1. **ndarray**

In [11]:
import numpy as np

## 1.1 属性

|属性|解释|
|---|---|
|`shape`|数组的形状（行数和列数）|
|`ndim`|维度数量：数组是几维的|
|`size`|总元素个数|
|`dtype`|元素类型|

In [22]:
list1 = [[1,2,3],[4,5,6]]
arr = np.array(list1,dtype=np.float64)
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

## 1.2 方法
1. `arr.copy()`可以拷贝数组，默认为深拷贝，即拷贝后的新数组和原数组没什么联系，修改新数组不会改变原数组

In [ ]:
arr_copy = arr.copy()
arr_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

## 1.3 生成特殊一维数组

2. `np.arange(start,end,step)`生成等差数列，左闭右开

In [25]:
arithmetic_sequence = np.arange(1,10,1)
arithmetic_sequence

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

3. `np.linspace(start,end,per)`生成等间隔数列，第三个参数`per`写入要等分的份数，左闭右闭

In [ ]:
linspace = np.linspace(1,10,5)
linspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

4. `np.logspace(start,end,per,base=底数)`生成等比数列，最后一个参数写底数

In [31]:
logspace = np.logspace(0,4,3,base=2,dtype=int)
logspace

array([ 1,  4, 16])

## 1.4 特殊矩阵

1. `np.eye(num)`定义单位矩阵，`num`值为行列

In [33]:
identity_matrix = np.eye(3,dtype=int)
identity_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

2. `np.diag([num1,num2,...])`定义对角矩阵，`num`值为主对角线的值

In [37]:
diagonal_matrix = np.diag([1,2,3])
diagonal_matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

3. `np.full((x,y),num)`可以生成指定行列的二维数组，并将数组全部填充`num`

In [39]:
arr_grow = np.full((3,3),0)
arr_grow

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## 1.5 随机数组

1. `random.rand(shape)`生成0~1之间的随机浮点数（均匀分布）

In [70]:
random1 = np.random.rand(2,3)
random1

array([[0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643]])

2. `random.uniform(start,end,(shape))`生成指定范围的随机浮点数（均匀分布）

In [44]:
random2 = np.random.uniform(3,6,(2,3))
random2

array([[5.79384887, 3.88368593, 3.58389134],
       [3.72714908, 4.7957089 , 3.08488832]])

3. `random.randint(start,end,(shape))`生成指定范围的随机整数（均匀分布）

In [45]:
random3 = np.random.randint(2,10,(3,4))
random3

array([[6, 5, 8, 8],
       [2, 4, 4, 6],
       [3, 5, 6, 3]], dtype=int32)

4. `random.randn(shape)`，生成随机浮点数数组（标准正态分布）

In [60]:
random4 = np.random.randn(2,3)
random4

array([[-1.68798546,  2.31521961, -1.84818214],
       [ 0.43365126,  0.59638802, -0.77566478]])

## 1.6 设置随机种子

#### 为什么需要随机种子
在生成随机数组时，每次生成的结果都不一样，但如果我们需要将结果复现给其他人看，不一样的随机数据最后呈现出来的肯定不一样，
所以为了保证复现一致，可以设置随机种子来保证生成的随机数组具有唯一性。

#### 设置方法
直接写 `np.random.seed(num)`，填入数字即可，数字可以随便填

In [68]:
np.random.seed(42) # 直接写，不需要赋给变量

random_array = np.random.randint(2,10,(3,4))
random_array

array([[8, 5, 6, 8],
       [4, 9, 6, 6],
       [8, 3, 4, 8]], dtype=int32)