# 1. ndarray

In [11]:
import numpy as np

## 1.1 属性

|属性|解释|
|---|---|
|`shape`|数组的形状（行数和列数）|
|`ndim`|维度数量：数组是几维的|
|`size`|总元素个数|
|`dtype`|元素类型|

In [22]:
list1 = [[1,2,3],[4,5,6]]
arr = np.array(list1,dtype=np.float64)
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

## 1.2 方法
1. `arr.copy()`可以拷贝数组，默认为深拷贝，即拷贝后的新数组和原数组没什么联系，修改新数组不会改变原数组

In [ ]:
arr_copy = arr.copy()
arr_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

2. `np.full((x,y),num)`可以生成指定行列的二维数组，并将数组全部填充`num`

In [24]:
arr_grow = np.full((3,3),0)
arr_grow

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])