# 2. 索引与切片

In [ ]:
import numpy as np

## 2.1 一维数组的索引与切片

In [ ]:
arr = np.random.randint(1,100,20)

array([39, 96, 61, 86, 99, 32, 74, 69,  3, 65, 77, 95, 30,  8, 50, 92, 99,
       39, 85, 86], dtype=int32)

In [22]:
print(arr[10]) # 索引
print(arr[:]) # 全部
print(arr[2:5]) # 切片（左闭右开）
print(arr[slice(2,15,3)]) # 切片函数 slice(start,end,step)
print(arr[(arr>50) & (arr<70)]) # 过滤

77
[39 96 61 86 99 32 74 69  3 65 77 95 30  8 50 92 99 39 85 86]
[61 86 99]
[61 32  3 95 50]
[61 69 65]


## 2.2 二维数组的索引和切片

In [23]:
arr2 = np.random.randint(1,100,(4,8))
arr2

array([[55, 51, 75,  6, 39, 62, 60, 54],
       [68, 49, 76, 79, 90, 43, 85, 46],
       [48, 62, 93, 87, 41, 10, 22, 48],
       [49,  9, 68, 10, 54, 60, 82, 91]], dtype=int32)

In [ ]:
print(arr2[1,3]) # 索引1【注意起始为(0,0)】
print(arr2[1][3]) # 索引2【注意起始为(0,0)】
print(arr2[:,:]) # 全部
print(arr2[2]) # 获取行
print(arr2[:,3]) # 获取列
print(arr2[1,2:5]) # 第1行，第2个到第4个
print(arr2[arr2>50]) # 过滤，输出一维数组
print(arr2[2][arr2[2]>50]) # 过滤第2行，挑出大于50的


79
79
[[55 51 75  6 39 62 60 54]
 [68 49 76 79 90 43 85 46]
 [48 62 93 87 41 10 22 48]
 [49  9 68 10 54 60 82 91]]
[76 79 90]
[55 51 75 62 60 54 68 76 79 90 85 62 93 87 68 54 60 82 91]
[62 93 87]
[ 6 79 87 10]
