# 3. 运算

In [1]:
import numpy as np

## 3.1 加减乘除
和普通的运算一样，没有用到矩阵乘法

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1 + arr2

array([5, 7, 9])

## 3.2 与标量相加
相当于数组的每个数都加上这个标量

In [5]:
arr11 = np.array([[1,2,3],[4,5,6]])
arr11 + 3

array([[4, 5, 6],
       [7, 8, 9]])

## 3.3 广播机制

In [6]:
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
a + b

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

## 3.4 矩阵乘法
`@` 定义矩阵乘法

In [10]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[4,5,6],[7,8,9],[10,11,12]])
arr1 @ arr2

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])