# 4. 基本函数

In [1]:
import numpy as np

## 4.1 数学函数

- 平方根 `np.sqrt()`

In [5]:
a = np.array([1,4,9])
np.sqrt(a)

array([1., 2., 3.])

- 以 $e$ 为底的指数 `np.exp()`

In [6]:
b = np.array([1,2,3])
np.exp(b)

array([ 2.71828183,  7.3890561 , 20.08553692])

- 以 $e$ 为底数的自然对数 `np.log()`

In [10]:
b = np.array(np.e)
np.log(b)

np.float64(1.0)

- 计算三角函数

In [15]:
c = np.sin(np.pi/2)
c

np.float64(1.0)

- 计算绝对值 `np.abs()`

In [17]:
d = np.abs(np.array([-1,2,5,-10]))
d

array([ 1,  2,  5, 10])

- 计算a的b次幂 `np.power(a,b)`

In [18]:
e = np.power(4,2)
e

np.int64(16)

- 四舍五入 `np.round()`

In [21]:
f = np.round([1.2,4.5,4.51,3.6])
f

array([1., 4., 5., 4.])

- 向上取整 `np.ceil()` / 向下取整 `np.floor()`

In [25]:
up = np.ceil([1.2,0.9,-2.1])
down = np.floor([1.2,0.9,-2.1])
up , down

(array([ 2.,  1., -2.]), array([ 1.,  0., -3.]))

- 检测缺失值 `np.isnan()`

In [31]:
arr = np.array([1.2, 9, np.nan, 666])
print(np.isnan(arr))
if True in np.isnan(arr):
    print("存在缺失值")

[False False  True False]
存在缺失值


## 4.2 统计函数

In [34]:
arr = np.random.randint(1,20,8)
arr

array([10, 11,  5,  9,  3,  1, 17,  3], dtype=int32)

- 求和 `np.sum()`

In [35]:
np.sum(arr)

np.int64(59)

- 平均值 `np.mean()`

In [36]:
np.mean(arr)

np.float64(7.375)

- 中位数 `np.median()` / 分位数 `np.percentile(arr,percent)`

In [51]:
np.median(arr),np.percentile(arr,50)

(np.float64(7.0), np.float64(7.0))

- 方差 `np.var()` / 标准差 `np.std()`

In [42]:
print("方差",np.var(arr))
print("标准差",np.std(arr))

方差 24.984375
标准差 4.998437255783052


- 最大值 `np.max()` / 最小值 `np.min()`
- 最大值索引 `np.argmax()` / 最小值索引 `np.argmin()`
- 每行最大值 `np.max(arr,axis=1)`
- 每列最大值 `np.max(arr,axis=0)`

In [47]:
print(np.max(arr),np.argmax(arr))

17 6


- 累积和 `np.cumsum()` / 累积积 `np.cumprod()`

假设原数组 $[a_1,a_2,a_3]$，则累积和 $[a_1,a_1+a_2,a_1+a_2+a_3]$

In [52]:
print("累积和",np.cumsum(arr))
print("累积积",np.cumprod(arr))

累积和 [10 21 26 35 38 39 56 59]
累积积 [    10    110    550   4950  14850  14850 252450 757350]


## 4.3 比较函数

- 是否大于num/otherArr `np.greater(arr,num)`

In [54]:
np.greater(arr,15)

array([False, False, False, False, False, False,  True, False])

- 是否小于num/otherArr `np.less(arr,num)`

In [56]:
np.less(arr,10)

array([False, False,  True,  True,  True,  True, False,  True])

- 是否等于num/otherArr `np.equal(arr,num)` 

In [57]:
np.equal(arr,8)

array([False, False, False, False, False, False, False, False])

- 逻辑与 `np.logical_and(arr1,arr2)`
- 逻辑或 `np.logical_or(arr1,arr2)`
- 逻辑非 `np.logical_not()`

In [63]:
print(np.logical_and([1,0],[1,1]))
print(np.logical_or([1,0],[1,1]))
print(np.logical_not([1,0]))

[ True False]
[ True  True]
[False  True]


- 检查是否至少有一个元素为 True `np.any(arr)`
- 检查是否全部为 True `np.all(arr)`

In [65]:
print(np.any([0,0,0,0,0]))
print(np.all([1,0,1,0,0]))

False
False


- 自定义条件 `np.where(条件,符合条件执行,不符合条件执行)`

In [66]:
arr_eg = np.array([1,2,3,4,5]) 
np.where(arr_eg<3,arr_eg,0)

array([1, 2, 0, 0, 0])

- 多区间条件 `np.select([条件],[结果],default='其他情况')`

In [68]:
score = np.array([30,60,80,90,40,60,70])
np.select([score<60,(score>=60)&(score<80),score>=80],['不及格','良好','优秀'],default='未知')

array(['不及格', '良好', '优秀', '优秀', '不及格', '良好', '良好'], dtype='<U3')

## 4.4 排序函数

In [70]:
np.random.seed(42)
arr_random = np.random.randint(1,100,20)
arr_random

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53,  2, 88,
       30, 38,  2], dtype=int32)

Python的数组本身就有`sort()`方法，不过会改变原数组<br />
NumPy库也有`sort()`方法，不会改变原数组

In [71]:
np.sort(arr_random)

array([ 2,  2,  3, 15, 21, 22, 24, 30, 38, 52, 53, 61, 72, 75, 75, 83, 87,
       88, 88, 93], dtype=int32)

去重 `np.unique()` <br />
计算每个唯一值出现的次数 `np.unique(arr,return_counts=True)`<br />
返回两个数组，例子可见 Q9

In [72]:
np.unique(arr_random)

array([ 2,  3, 15, 21, 22, 24, 30, 38, 52, 53, 61, 72, 75, 83, 87, 88, 93],
      dtype=int32)

拼接数组 `np.concatenate()`

In [ ]:
# 创建示例数组
a = np.array([[1, 2], [3, 4]])  # 2x2
b = np.array([[5, 6], [7, 8]])  # 2x2

# 沿行方向拼接（axis=0，垂直拼接）
result1 = np.concatenate((a, b), axis=0)
# array([[1, 2],
#        [3, 4],
#        [5, 6],
#        [7, 8]])  # 4x2

# 沿列方向拼接（axis=1，水平拼接）
result2 = np.concatenate((a, b), axis=1)
# array([[1, 2, 5, 6],
#        [3, 4, 7, 8]])  # 2x4

调整数组形状 `np.reshape()`

In [76]:
np.reshape(result2,[4,2])

array([[1, 2],
       [5, 6],
       [3, 4],
       [7, 8]])