In [2]:
import numpy as np

## Q1：温度数据分析
某城市一周的最高气温（℃）为 [ 28, 30, 29, 31, 32, 30, 29 ]
- 计算平均气温、最高气温、最低气温
- 找出气温超过30℃的天数

In [3]:
temperature = np.array([28, 30, 29, 31, 32, 30, 29])
max_temp = np.max(temperature)
min_temp = np.min(temperature)
avg_temp = np.mean(temperature)
day = np.size(temperature[temperature>30]) # 方法1
day2 = np.sum(temperature>30) # 方法2

print(f"最高{max_temp}℃ 最低{min_temp}℃ 平均{avg_temp:.2f}℃")
print(f"气温超过30℃的天数：{day2}")

最高32℃ 最低28℃ 平均29.86℃
气温超过30℃的天数：2


## Q2：学生成绩统计
某班级5名学生的数学成绩为 [ 85, 80, 78, 92, 88 ]
- 计算成绩的平均分
- 将成绩转换为十分制（假设满分为10分）

In [10]:
score = np.array([85, 90, 78, 92, 88])
avg_score = np.mean(score)
median_score = np.median(score)
std_score = np.std(score)
ten = score / 10

print(f"平均分：{avg_score:.2f} 中位数：{median_score:.2f} 标准差：{std_score:.2f}")
print(f"十分制：{ten}")

平均分：86.60 中位数：88.00 标准差：4.88
十分制：[8.5 9.  7.8 9.2 8.8]


## Q3：矩阵运算
给定矩阵 A = [[1, 2], [3, 4]] 和 B = [[5, 6], [7, 8]] 
- 计算 A + B 和 A * B
- 计算 A 和 B 的矩阵乘法

In [16]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(f"A + B :\n {A+B} \n A * B : \n{A * B} \n A @ B : \n{A @ B}")

A + B :
 [[ 6  8]
 [10 12]] 
 A * B : 
[[ 5 12]
 [21 32]] 
 A @ B : 
[[19 22]
 [43 50]]


## Q4：随机数据生成
生成一个 (3，4) 的随机整数数组，范围 [0, 10)
- 计算每列的最大值和每行的最小值
- 将数组中所有奇数替换为 -1

In [ ]:
np.random.seed(0)
arr_random = np.random.randint(0,10,(3,4))
row_max = np.max(arr_random,axis=0)
line_min = np.min(arr_random,axis = 1)
instead_odd = np.where(arr_random % 2 == 1,-1,arr_random)

print(arr_random)
print(f"每列最大值：{row_max} 每行最小值：{line_min}")
print(f"替换：\n {instead_odd}")

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列最大值：[7 9 7 6] 每行最小值：[0 3 2]
替换：
 [[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


## Q5：数组变形
创建一个 1 到 12 的一维数组，并转换为 (3, 4) 的二维数组
- 计算每行的和与每列的平均值
- 将数组展平为一维数组

In [36]:
arr2 = np.arange(1,13)
reshape = np.reshape(arr2,(3,4))
line_sum = np.sum(reshape,axis=1)
row_avg = np.mean(reshape,axis=0)
d1 = np.reshape(reshape,(12))

print(arr2)
print(reshape)
print(f"每行的和：{line_sum}")
print(f"每列的平均值：{row_avg}")
print(f"转换为1维数组：{d1}")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和：[10 26 42]
每列的平均值：[5. 6. 7. 8.]
转换为1维数组：[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Q6：布尔索引
生成一个 (5, 5) 的随机数组，范围 [0, 20)
- 找出数组中大于10的元素
- 将所有大于10的元素替换为0

In [10]:
np.random.seed(1)
arr_ran2 = np.random.randint(0,20,(5,5))

print(arr_ran2)
print("大于10的元素\n",arr_ran2[arr_ran2>10])
print('大于10替换为0\n',np.where(arr_ran2>10,0,arr_ran2))

[[ 5 11 12  8  9]
 [11  5 15  0 16]
 [ 1 12  7 13  6]
 [18  5 18 11 10]
 [14 18  4  9 17]]
大于10的元素
 [11 12 11 15 16 12 13 18 18 11 14 18 17]
大于10替换为0
 [[ 5  0  0  8  9]
 [ 0  5  0  0  0]
 [ 1  0  7  0  6]
 [ 0  5  0  0 10]
 [ 0  0  4  9  0]]


## Q7：统计函数的应用
某公司 6 个月的销售额（万元）为 [120, 135, 110, 125, 130 ,140]
- 计算销售额总和、平均值、方差
- 找出销售额最高的月份和最低的月份

In [16]:
sales = np.array([120,135,110,125,130,140])
sales_sum = np.sum(sales)
sales_avg = np.mean(sales)
sales_var = np.var(sales)
max_month = np.argmax(sales) + 1
min_month = np.argmin(sales) + 1

print(f"总额：{sales_sum}万元 均值：{sales_avg:.2f}万元 方差：{sales_var:.2f}万元")
print(f"最高月：{max_month}月 最低月：{min_month}月")

总额：760万元 均值：126.67万元 方差：97.22万元
最高月：6月 最低月：3月


## Q8：数组拼接
给定 A = [1, 2, 3] 和 B = [4, 5, 6]
- 将 A 和 B 水平拼接为一个新数组
- 将 A 和 B 垂直拼接为一个新数组

In [ ]:
A8 = np.array([1,2,3])
B8 = np.array([4,5,6])

print("水平拼接\n",np.concatenate((A8,B8)))
print("垂直拼接\n",np.vstack((A8,B8)))

# 垂直拼接如果坚持用 concatenate，需要将两个数组转为2维数组，因为一维数组没有行的概念
A2d = A8.reshape(1, -1)
B2d = B8.reshape(1, -1)
result = np.concatenate((A2d, B2d), axis=0)
print(result)

水平拼接
 [1 2 3 4 5 6]
垂直拼接
 [[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


## Q9：唯一值与排序
给定数组 [2, 1, 2, 3, 1, 4, 3]
- 找出唯一值并排序
- 计算每个唯一值出现的次数

In [35]:
arr9 = [2,1,2,3,1,4,3]
arr_unique,count = np.unique(arr9,return_counts=True)

print(arr_unique)
print(count)

[1 2 3 4]
[2 2 2 1]


## Q10：综合应用
某商店 5 天的销售额（万元）和成本如下：<br />
销售额：[20, 25, 22, 30, 28] <br />
成本：[15, 18, 16, 22, 20]
- 计算每天的利润
- 计算利润的平均值与标准差
- 找出利润最高的天数，并找出是哪几天

In [44]:
turnover = np.array([20,25,22,30,28])
cost = np.array([15,18,16,22,20])

profit = turnover - cost
profit_avg = np.mean(profit)
profit_std = np.std(profit)
profit_max_day = np.where(profit == np.max(profit))
profit_max_count = np.size(profit[profit==np.max(profit)])

print(f"每天利润：{profit} 利润均值：{profit_avg:.2f} 利润标准差：{profit_std:.2f}")
print(f"利润最高的天数：{profit_max_count}天 {profit_max_day}")

每天利润：[5 7 6 8 8] 利润均值：6.80 利润标准差：1.17
利润最高的天数：2天 (array([3, 4]),)
